### ISSUE TITLE
RuntimeException on PHPUnit Symlink Creation

### ISSUE THREAD

**Issue by mostertb** [afrihost/code-kata-base#4]
Running `composer install` more than once results in the following error due to the symlink already existing 

```
Script ln -s vendor/phpunit/phpunit/phpunit phpunit handling the post-install-cmd event returned with an error
  [RuntimeException]
  Error Output: ln: phpunit: File exists
```

This makes actions such as updating the autoloader impossible

**Comment by johnathanmdell** [comment]
Thanks for the heads up on this :+1: 

Even though I agree this is a bug, it does not affect what the code kata base was created for (once off uses).

**Comment by mostertb** [comment]
Agreed. To tell you the truth, I was just testing the Issue feature on a repo I dont own ;)

Looks like @sarelvdwalt fixed this in 5bd646758c1b142a912b2f7a2ddbc2b4403b934b . I think we can close this issue

**Comment by sarelvdwalt** [comment]
Oh cool, didn't even realize there was an issue about this opened :) Yup, this fixes the issue :)

**Comment by johnathanmdell** [comment]
Closing issue
